[basic]
api_base="https://maas-api.cn-huabei-1.xf-yun.com/v1"
model="xdeepseekv31"
api_key="sk-xxxxxxx16E165Bd"

[clarify]
api_base="https://maas-api.cn-huabei-1.xf-yun.com/v1"
model="xdeepseekv31"
api_key="sk-xxxxxxx16E165Bd"

[planner]
api_base="https://maas-api.cn-huabei-1.xf-yun.com/v1"
model="xdeepseekr1"
api_key="sk-xxxxxxx16E165Bd"

[query_generation]
api_base="https://maas-api.cn-huabei-1.xf-yun.com/v1"
model="xdeepseekv31"
api_key="sk-xxxxxxx16E165Bd"

[evaluate]
api_base="https://maas-api.cn-huabei-1.xf-yun.com/v1"
model="xdeepseekv31"
api_key="sk-xxxxxxx16E165Bd"

[report]
api_base="https://maas-api.cn-huabei-1.xf-yun.com/v1"
model="xdeepseekv31"
api_key="sk-xxxxxxx16E165Bd"